#!/bin/bash

set -e

script_dir=$(cd "$(dirname "$0")" ; pwd -P)
usage() { echo "Usage: $0 [-p <project name: string>] [-m <module name: string>] [-r <aws region: string>]" 1>&2; exit 1; }

while getopts ":p:m:r:" o; do
    case "${o}" in
        p)
            project=${OPTARG}
            ;;
        m)
            module=${OPTARG}
            ;;
        r)
            region=${OPTARG}
            ;;
        *)
            usage
            ;;
    esac
done
shift $((OPTIND-1))

if [ -z "${project}" ] || [ -z "${module}" ] || [ -z "${region}" ]; then
    usage
fi

replace_params() {
  target_file=${1}
  if [ -z "${target_file}" ]; then
    echo "TARGET_FILE missing. Usage: <func: replace_params> target_file"
    exit 1
  fi

  if [ $OSTYPE == "linux-gnu" ]; then
    sed -i -e s/example1\-example2/${module}/g "${target_file}"
    sed -i -e s/example\-project/${project}/g "${target_file}"
    sed -i -e s/project\-aws\-region/${region}/g "${target_file}"
  else
    sed -i '' -e s/example1\-example2/${module}/g "${target_file}"
    sed -i '' -e s/example\-project/${project}/g "${target_file}"
    sed -i '' -e s/project\-aws\-region/${region}/g "${target_file}"
  fi
}

pushd "${script_dir}" > /dev/null
  workflow_path=".github/workflows"
  template_files="example-build-test-deploy.yml.tpl example-delete-aws-resources.yml.tpl example-delete-github-runner.yml.tpl"
  for i in $template_files
  do
    filename_without_example="${i//"example-"/}"
    filename_without_tpl="${filename_without_example//".tpl"/}"
    echo "Creating ${script_dir}/${workflow_path}/${filename_without_tpl}"
    cp "${workflow_path}/${i}" "${workflow_path}/${filename_without_tpl}"
    replace_params "${workflow_path}/${filename_without_tpl}"
  done

popd > /dev/null

